# slurm_cluster.yml - cluster configuration for elvers
__default__:
    account: mc5phkp
    partition: RM-small
    time: 01:00:00
    nodes: 2
    ntasks-per-node: 28 #Request n cores be allocated per node.    
    cpus-per-task: 14
    chdir: /pylon5/mc5phkp/ntpierce
    output: /pylon5/mc5phkp/ntpierce/mmetsp_out/logs/preprocess-%j.out
    error: /pylon5/mc5phkp/ntpierce/mmetsp_out/logs/preprocess-%j.err

#    mem: 20G
# cpus-per-task: 14
